### ISSUE TITLE
Update stable version in repo from 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by GermanBluefox** [Excodibur/ioBroker.schwoerer-ventcube#46]
# Think about update stable version to 1.4.0
**Version**: stable=**1.3.0** (234 days old) => latest=**1.4.0** (15 days old)
**Installs**: stable=**447** (97.39%), latest=**12** (2.61%), total=**459**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1435)

**Comment by Excodibur** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1298

PR to update stable to 1.4.1 (currently latest)
