### ISSUE TITLE
Modbus address of T6 not correct

### ISSUE THREAD

**Issue by iobroker007** [Excodibur/ioBroker.schwoerer-ventcube#60]
According to the Modbus TCP list of Schwörer, the Modbus address has to be 205 (and not 204) for T6 in WT.

extract of "ioBroker.schwoerer-ventcube/src/lib/schwoerer/parameters.ts":
"t6-in-wt":    {        descr: "T6 im WT",        category: "advanced",        modbus_r: 204,        modbus_w: -1,        value_type: "range",        value_def: {            min: -50,            max: 100,            unit: "°C"        }

It would be very nice to get that fixed.
Thank you very much in advance!

**Comment by iobroker007** [comment]
Modbus TCP list of Schwörer: 
https://schwoerer-service.com/storage/files/Community/2020/Parameterliste_Modbus_TCP_032020.pdf

**Comment by Excodibur** [comment]
Thanks for reporting it! I'll take a look at it tomorrow!

**Comment by Excodibur** [comment]
I merged your PR into the adapter code now and included it in release 1.4.1. It is available in latest-repo already, and a PR to get it into the stable repo was raised as well.

Again, thanks for rasing the issue and providing a PR!
