### ISSUE TITLE
Link der Parameterliste nicht mehr aktuell

### ISSUE THREAD

**Issue by marschallphilipp** [Excodibur/ioBroker.schwoerer-ventcube#89]
Hallo Yarn :-)
Der Link der Parameterliste ist leider nicht mehr aktuell und ich finde sie ansonsten nirgends im Netz, hast du sie evtl. noch?

Vielen Dank!

**Comment by Excodibur** [comment]
Hallo Philipp,

Lightyarn bin ich tatsächlich nicht, auch wenn ich ab und an mit ihm in Kontakt stehe. :-)

Ich glaube der Link funktioniert nicht mehr, weil Schwörerhaus sein Kundenportal erneuert hat. Ich bin auch fast wieder soweit, dass ich Zugang habe, d.h. dann kann ich den Link ggf. nochmal aktualisieren.

Hier ist die letzte mir bekannt Version:
[Parameterliste_Modbus_TCP_032020.pdf](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/files/7021640/Parameterliste_Modbus_TCP_032020.pdf)

Gruß
Excodibur ;-)

**Comment by marschallphilipp** [comment]
> Hallo Philipp,
> 
> Lightyarn bin ich tatsächlich nicht, auch wenn ich ab und an mit ihm in Kontakt stehe. :-)
> 
> Ich glaube der Link funktioniert nicht mehr, weil Schwörerhaus sein Kundenportal erneuert hat. Ich bin auch fast wieder soweit, dass ich Zugang habe, d.h. dann kann ich den Link ggf. nochmal aktualisieren.
> 
> Hier ist die letzte mir bekannte Version:
> [Parameterliste_Modbus_TCP_032020.pdf](https://github.com/Excodibur/ioBroker.schwoerer-ventcube/files/7021640/Parameterliste_Modbus_TCP_032020.pdf)
> 
> Gruß
> Excodibur ;-)

Sorry :-) Hatte nur mitbekommen, dass er an einem Adapter für den Ventcube gearbeitet hatte und ich dachte, das wäre dieser....
Vielen Dank für das Dokument!
